name: Code Ranking

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0,4-23 * * 0-6'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: 
        npm install

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: '1118540'
      
    - name: Check Chrome
      run: chrome --version

    - name: Update Code Ranking
      run: node code-ranking-updater.js ${{vars.URL}} ${{secrets.EMAIL}} ${{secrets.PASSWORD}}
