name: Code Ranking

on:
  schedule:
    - cron: '1 0,6-22/2 * * 0,3,5,6'
    - cron: '4 7-23/2 * * 0,3,5,6'
    - cron: '6 0,6-22/2 * * 1,2,4'
    - cron: '9 7-23/2 * * 1,2,4'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
      
    - name: Check Chrome
      run: chrome --version

    - name: Update Code Ranking
      run: node code-ranking-updater.js
